set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

# Rack-SDK uses the old C runtime...
set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled)
# set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
