name: ubuntu

on:
  # Runs on all pushes
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ubuntu-latest-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0
  BUILD_DIR: ${{ github.workspace }}/build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_INSTALL_PARALLEL_LEVEL: 3
  RACK_SDK_VERSION: 2.5.2
  RACK_SDK_PLATFORM: "lin-x64"

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:

      # REQUIREMENTS

    - name: Checkout StoneyVCV code
      uses: actions/checkout@v4
      with:
        submodules: true

      # https://vcvrack.com/manual/Building#Setting-up-your-development-environment
    - name: Install VCV's Linux Deps
      run: |
        sudo apt-get update && sudo apt install unzip git gdb curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libgtk-3-dev libjack-jackd2-dev jq zstd libpulse-dev pkg-config ninja-build ccache tree

    - name: Fetch Rack SDK
      run: |
        mkdir dep
        curl https://vcvrack.com/downloads/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip -o ./dep/Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd dep
        unzip Rack-SDK-${{env.RACK_SDK_VERSION}}-${{env.RACK_SDK_PLATFORM}}.zip
        cd ..

      # DEVELOPER WORKFLOW

    - name: Configure
      env:
        RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK
      run: >-
        cmake
        --preset x64-linux-release
        --fresh

    - name: Install
      run: >-
        cmake
        --install ${{ env.BUILD_DIR }}
        --prefix ${PWD}/install
        --strip
        -j 3

    # DEPLOYMENT WORKFLOW

    - name: Package
      env:
        RACK_DIR: ${{ github.workspace }}/dep/Rack-SDK
      run: make package -j3

    # List all files in install tree
    - name: Tree
      run: |
        cd install
        tree
        cd ..
